//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudikka.PolylineAlgorithm {
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ExceptionMessageResource {
		#region Fields

		/// <summary>
		/// Defines the resourceCulture
		/// </summary>
		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Defines the resourceMan
		/// </summary>
		private static global::System.Resources.ResourceManager resourceMan;

		#endregion

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the <see cref="ExceptionMessageResource"/> class.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ExceptionMessageResource() {
		}

		#endregion

		#region Properties

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloudikka.PolylineAlgorithm.ExceptionMessageResource", typeof(ExceptionMessageResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source char array argument cannot be null -or- empty.
		/// </summary>
		internal static string SourceCharArrayCannotBeNullOrEmpty {
			get {
				return ResourceManager.GetString("SourceCharArrayCannotBeNullOrEmpty", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source coordinates argument is invalid.
		/// </summary>
		internal static string SourceCoordinatesAreInvalid {
			get {
				return ResourceManager.GetString("SourceCoordinatesAreInvalid", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source polyline argument cannot be null -or- empty.
		/// </summary>
		internal static string SourcePolylineStringCannotBeNullOrEmpty {
			get {
				return ResourceManager.GetString("SourcePolylineStringCannotBeNullOrEmpty", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Source polyline argument is malformed.
		/// </summary>
		internal static string SourcePolylineStringIsMalformed {
			get {
				return ResourceManager.GetString("SourcePolylineStringIsMalformed", resourceCulture);
			}
		}

		#endregion
	}
}
